### ISSUE TITLE
Opped players do not lose items on death.

### ISSUE THREAD

**Issue by instaaftereffects** [eccentricdevotion/GameModeInventories#20]
For some reason, when the plugin is installed and an opped player dies, their items will empty their inventory during their death animation, but then when they respawn, their items will appear back in their inventory. (Their experience and level drops if they're in survival, though)

How to recreate: 
- Install plugin
- Op Player
- /kill Player

If you remove the plugin, and /kill the opped player, their items will drop perfectly.

**Comment by eccentricdevotion** [comment]
Negate the `gamemodeinventories.death` permission - it defaults to `true` for opped players

**Comment by eccentricdevotion** [comment]
```
permissions:
  gamemodeinventories.use:
    default: true
    description: Allow players to have separate inventories for each gamemode.
  gamemodeinventories.death:
    default: op
    description: Allow players to save their inventories on death, and restore them on respawn.
  gamemodeinventories.bypass:
    default: op
    description: Allow players to access inventories in CREATIVE mode even if 'restrict_creative' is true. Also allow CREATIVE players to drop and pickup items.
  gamemodeinventories.spectator:
    default: op
    description: Allow players to switch to Gamemode SPECTATOR.
  gamemodeinventories.admin:
    default: op
    description: Allow players to change config options.
```
